version: '3'

services:
  db:
    image: postgres:9.6.12
    container_name: db
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - DATABASE_PORT=5432
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - app-network
  
  app:
    container_name: app
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
    depends_on:
      - db
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network: